using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using WorkShop4.Models;


namespace WorkShop4
{
    public partial class AddSuppliersFrm : Form
    {
        public TravelExpertsContext context = new TravelExpertsContext();

        public Supplier currentSupplier { get; set; }

        private Supplier supplier = null;
        public bool AddButton { get; set; }

        public AddSuppliersFrm()
        {
            InitializeComponent();
        }

        private void saveSupplierBtn_Click(object sender, EventArgs e)
        {
            supplier = new Supplier
            {
                SupplierId = Convert.ToInt32(SupplierIdTxt.Text),
                SupName = supNameTxt.Text
            };

            if (AddButton == true)
                context.Suppliers.Add(supplier);

            else
                context.Suppliers.Update(supplier);
                context.SaveChanges();
            MessageBox.Show("Record inserted successfully");
            this.Close();

            //supplier = new Supplier();

            //context.Suppliers.Update(supplier);
            //MessageBox.Show("Supplier details updated");

            //context.SaveChanges();
            //Display();
            //this.Close();

            //supplier = new Supplier();

            //supplier.SupplierId = Convert.ToInt32(SupplierIdTxt.Text);
            //supplier.SupName = supNameTxt.Text;

            //context.Suppliers.Add(supplier);
            //MessageBox.Show("Supplier added");

            //context.SaveChanges();

            //this.Close();
        }

        private void cancelSupplierBtn_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void AddSuppliersFrm_Load(object sender, EventArgs e)
        {
           if (AddButton == true) // user clicked add
            {
                //SupplierIdTxt.Enabled = false; - this is when id is autogenerated
                //SupplierIdTxt.Text = "0"; - this is when id is autogenerated
                SupplierIdTxt.Text = "";
                supNameTxt.Text = "";
            }
            else //user clicked Modify
            {
                SupplierIdTxt.Enabled = false;
                SupplierIdTxt.Text = currentSupplier.SupplierId.ToString();
                supNameTxt.Text = currentSupplier.SupName;
            }
        }

        private void supNameTxt_Validating(object sender, CancelEventArgs e)
        {
            if (supNameTxt.Text.Length <= 1)
            {
                MessageBox.Show("Supplier name cannot be empty");
                supNameTxt.Focus();
            }
        }
    }
}
